- name: Deploy Apache on Ubuntu EC2
  hosts: ubuntu_nodes
  vars:
    service: apache2

  tasks:
    - name: Update apt package manager
      ansible.builtin.apt:
        name: '*'
        state: latest
    - name: Install apache2
      ansible.builtin.apt:
        name: "{{ service }}"
        state: present
    - name: Start Apache2 service, if not started
      ansible.builtin.service:
        name: "{{ service }}"
        state: started
    - name: Enable apache on boot
      ansible.builtin.service:
        name: "{{ service }}"
        enabled: yes
    - name: Ensure /var/www/html directory exists
      file:
        path: /var/www/html
        state: directory
    - name: Copy index.html to Apache web root
      ansible.builtin.copy:
        src: index.html
        dest: /var/www/html